### ISSUE TITLE
关于公式上的一些请教

### ISSUE THREAD

**Issue by wyzhhhh** [ChanLiang/CONNER#1]
作者您好，请问论文中的公式提到的NLI()指的是ColbertV2这类模型吗，例如Factuality这部分公式计算具体是如何操作得到的，有一点搞不清楚，烦请作者赐教！感谢！

**Comment by ChanLiang** [comment]
Dear user,

Thank you for your interest in our work! The NLI model referred to in the paper is indeed a Roberta-NLI, whereas ColbertV2 is a retrieval model. The specific computation for the Factuality section can be found in the paper, and we will be updating our GitHub repository with code that should clarify this in the near future. We appreciate your patience and your interest in our research.

Kind Regards
